### ISSUE TITLE
nice work. could you provide amc2023 and aime 2024 dataset and evaluation script

### ISSUE THREAD

**Issue by yyht** [hkust-nlp/dart-math#1]
nice work. will you release amc2023 and aime 2024 dataset and evaluation script which was posted on https://x.com/tongyx361/status/1815112376649134172

**Comment by tongyx361** [comment]
Sorry that the evaluation on AMC2023 and AIME2024 is conducted by the Numina team, so I don't have the exact evaluation datasets and scripts.

You can try
1. opening an issue in [their repo.](https://github.com/project-numina/aimo-progress-prize?tab=readme-ov-file),
2. constructing your own versions with [the AOPS dataset provided in the repo., which does not include the problems in 2024](https://github.com/hkust-nlp/dart-math/blob/main/data/dsets/aops.jsonl),
3. crawling from [the AOPS website](https://artofproblemsolving.com/wiki/index.php).
